### ISSUE TITLE
LangGraph fails to detect docker is running

### ISSUE THREAD

**Issue by sammcj** [langchain-ai/langgraph-studio#176]
> Failed to start project
> Error invoking remote method 'up': Error: Docker not installed or not running: ExecaError: Command failed with ENOENT: docker info -f json
> spawn docker ENOENT

However Docker is running normally and works with other applications without issue:

```shell
docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

colima status
INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: virtiofs
INFO[0000] socket: unix:///Users/samm/.colima/default/docker.sock
```

<img width="710" alt="image" src="https://github.com/user-attachments/assets/1de39f44-b92d-4848-865d-09ccbb26bea2">

<img width="576" alt="image" src="https://github.com/user-attachments/assets/ff33bb5a-5667-4ae9-a582-c29b7fb43634">

**Comment by Josako** [comment]
I have a similar problem. However, it gives the following error:

![image](https://github.com/user-attachments/assets/23577f65-9ebf-4bcc-a2c6-96aea68f62af)

**Comment by dqbd** [comment]
Hello @sammcj! Would it be possible to share the output of the following command? 

`dscl . -read ~/ UserShell | sed 's/UserShell: //'`

**Comment by sammcj** [comment]
```
dscl . -read ~/ UserShell | sed 's/UserShell: //'
/bin/zsh
```

**Comment by unlisted** [comment]
having the same issue, and the fix in #37 is not working for me.
```
~$>dscl . -read ~/ UserShell | sed 's/UserShell: //'
/opt/homebrew/bin/bash
~$>/bin/zsh -c 'open /Applications/LangGraph\ Studio.app/'
```
![Screenshot 2024-11-03 at 7 14 18 PM](https://github.com/user-attachments/assets/cfb5ba32-0112-45b4-8760-272327501b74)

```
$>docker info -f json
{"ID":"bf816ee3-7c2e-44c5-a117-4a56f31c4695","Containers":0,"ContainersRunning":0,"ContainersPaused":0,"ContainersStopped":0,"Images":52,"Driver":"overlay2","DriverStatus":[["Backing Filesystem","extfs"],["Supp
...
```

**Comment by sammcj** [comment]
Confirming this is fixed. Thanks!

**Comment by SanjuMLGeek** [comment]
I am still facing the issue after reinstalling 0.0.30 version

Error is 

`Failed to start project langgraph-example
Error invoking remote method 'up': Error: Docker not installed or not running: ExecaError: Command failed with exit code 1: which docker`

I checked docker parth and it is as below

`(base) ➜  ~ which docker
/Users/<User>/.rd/bin/docker`

Docker is also running

`(base) ➜  ~ docker info
Client:
 Version:    25.0.4-rd
 Context:    default
 Debug Mode: false`

**Comment by bhaktatejas922** [comment]
same issue, m1 mac.
