### ISSUE TITLE
ERROR:  extension "vector" is not available

### ISSUE THREAD

**Issue by daflood** [langchain-ai/langgraph-studio#221]
I get this error, "ERROR:  extension "vector" is not available" if I try to load my project based on the LangGraph Memory Agent on any version of Langgraph Studio after 0.0.32.

**Comment by daflood** [comment]
Were you able to replicate this? Will it be resolved in a later update? It would be nice to be able to use newer versions with my project. I was seeing that error after fresh installs with just the default memory agent template.

**Comment by dqbd** [comment]
Ah, we've merged in a PR, but the issue will be closed with next release

**Comment by dqbd** [comment]
Should be fixed with 0.0.35!

**Comment by daflood** [comment]
Thanks! .35 is working great but it looks like the missing vector extension still isn't loading in the CLI version of Langgraph. I reported the bug on the main Langgraph github page.

**Comment by dqbd** [comment]
Hello! Will update the Python CLI as well, sorry about that!
